INSERT INTO `UserProperty`(`name`) values('共性');
INSERT INTO `UserProperty`(`name`) values('领导');
INSERT INTO `UserProperty`(`name`) values('教师');
INSERT INTO `User`(`user_property_id`, `name`, `branch`, `isAdmin`) values(3, 'gangpu', 'Shannxi', 1);
INSERT INTO `User`(`user_property_id`, `name`, `branch`, `isAdmin`) values(1, 'xzgan', 'henan', 1);
INSERT INTO `User`(`user_property_id`, `name`, `branch`, `isAdmin`) values(2, 'test', 'test', 0);
INSERT INTO `PaperTest`(`name`) values('教师师德师风自查');
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '您是否能切实做到上课前面对镜子正衣冠，保持微笑，以良好的精神面貌进入课堂。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '在平常的工作中，您是否能做到对于学习困难学生、犯了错误的学生不讽刺、挖苦、歧视。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '您在平时的教学中，是否能刻苦钻研业务，不断学习新知识，探索教育教学规律，改进教育教学方法。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '您在教学中是否能做到针对不同班级学生特点有针对性的备课上课，因材施教。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '您在课后批改作业时是否能关注到重点学生并有针对性的进行批注。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '您是否注重培养学生良好品行，激发学生创新精神，不以分数作为评价学生的唯一标准。(10分） ', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '在与同事相处时，您是否能做到尊重同事、团结协作、相互学习、相互帮助，维护其他教师在学生中的威信。(10分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '有没有过对特殊孩子进行单独辅导与教育？（一月平均共计20次，每次计0.5分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '有没有过与所带班级的班主任关于孩子（学习、纪律等）进行沟通了解？（一月平均共计20次，每次计0.5分）', 1);
INSERT INTO `PaperQuestion`(`user_property_id`, `description`, `test_id`) values(1, '有没有利用家长接送孩子的时机与家长进行有效沟通？（一月平均共计20次，每次计0.5分）', 1);
INSERT INTO `PaperOption`(`description`,`test_id`) values('优秀', 1);
INSERT INTO `PaperOption`(`description`,`test_id`) values('良好', 1);
INSERT INTO `PaperOption`(`description`,`test_id`) values('一般', 1);
INSERT INTO `PaperOption`(`description`,`test_id`) values('较差', 1);