INSERT INTO `UserProperty`(`name`) values('共性');
INSERT INTO `UserProperty`(`name`) values('村（社区）党员');
INSERT INTO `UserProperty`(`name`) values('“两新”组织党员');
INSERT INTO `UserProperty`(`name`) values('机关企事业党员');
INSERT INTO `UserProperty`(`name`) values('党员领导干部');
INSERT INTO `User`(`user_property_id`, `name`, `realName`, `branch`, `organization`, `isAdmin`) values(3, 'gangpu', 'pugang', 'Shannxi', 'ibm', 1);
INSERT INTO `User`(`user_property_id`, `name`, `realName`, `branch`, `organization`, `isAdmin`) values(4, 'xzgan', 'ganxiangzhen', 'henan', 'google', 1);
INSERT INTO `User`(`user_property_id`, `name`, `realName`, `branch`, `organization`, `isAdmin`) values(2, 'test', 'test', 'Shannxi', 'ibm', 0);
INSERT INTO `User`(`user_property_id`, `name`, `realName`, `branch`, `organization`, `isAdmin`) values(2, 'test1', 'test1', 'Shannxi', 'ibm', 0);
INSERT INTO `PaperTest`(`name`) values('党性体检参考指标');
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '能不能够做到在任何情况下政治信仰不变、政治立场不移、政治方向不偏，始终按照党的决策和要求积极提升自己的党性修养？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '能不能关键时刻站得出，危险时刻豁得出，如有危难降临，能否随时准备为党和人民牺牲一切？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '当听到周围的党员群众妄议组织的工作决策部署时，能不能够做到出面制止他们，并加以正确引导？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '能不能做到认真参加每一次组织生活、诵读一遍党章、按时足额亲自交纳党费，并按照《党章》的要求履行党员的义务？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '在日常生活物质需求上，能不能够做到勤俭节约、艰苦朴素、量力而行，不跟风攀比、大操大办？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '在考虑问题的时候，能不能够做到站在集体的角度、发展的角度来思考和解决问题，并做到言行一致、表里如一？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '在日常生产生活过程中，能不能主动维护党的形象，不说与党员身份不相符的话，在公众场合及微信、QQ等平台能不能管住自己的言行举止？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '能不能够做到与各种不文明行为作斗争，不参与封建迷信、打架斗殴、聚众赌博、缠访闹访等?', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '能不能够带头弘扬中华民族传统美德，积极引导身边的人讲道德、遵道德、守道德，并时时处处规范自己的言行，用自己的模范言行为身边的人做出榜样？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '在日常生产生活中与他人产生纠纷时，能不能够做到按照国家法律法规、社会公德的标准和要求自行妥善处理？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '当个人及家庭的事业有所成就的时候，能不能够做到谦虚谨慎、低调为人、真诚待人？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '正确理解“孝”的含义，能不能够做到按照“你把养大，陪你变老”的理念待好自己家里的老人和父母?', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '党员应该吃苦在前，享受在后，工作上是不是始终坚持积极主动高标准？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '党组织开展各项公益活动、志愿服务等活动时，在没有经济激励和报酬的前提下，能不能够做到积极参加？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '遇到困难群体时，能不能尽自己的力量奉献一份爱心？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 1, '在人民群众生命财产安全受到威胁时，能不能够挺身而出？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 2, '能不能够做到在村（社区）内不私搭乱建、不乱停车、不随意丢弃、倾倒生活垃圾，保持屋内外环境卫生整洁？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 2, '在村（社区）换届过程中，能不能严守换届纪律、正确行使党员权利，做到不拉票、不贿选、不吃请、不造谣诽谤他人、不破坏选举会场等？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 2, '能不能够做到按照无职党员设岗定责的规定在固定时间进行履职，按照党员公开承诺进行践诺、评诺，并发挥先锋模范作用？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 2, '能不能够做到及时关心村（社区）内不安定因素，主动调解各类纠纷，收集群众意见并反馈到党组织？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 3, '能不能够做到积极维护各方合法权益，反映职工诉求，依法维护职工合法权益，协调各方利益关系，及时化解矛盾纠纷，促进社会稳定？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 3, '在生产经营时，能不能够做到依法经营、诚信经营，按照市场经济的规律和规则抓好生产，坚决杜绝“散乱污”，做好服务？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 3, '在发展生产、新建项目之前，能不能够做到对项目进行环境和秩序上的考虑，以避免周边生态环境、公共秩序的破坏，或者对他人的权益造成侵害？ ', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 3, '是否能够遵守职业道德，积极参与丰富多彩的企业文化活动，带头在本职岗位上做出优异成绩？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 4, '能不能够带头贯彻执行党组织各项决策部署，服从组织分配，积极完成党组织交给的任务？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 4, '在接待群众上是否能做到耐心热情，深入细致的询问所办事项，积极解决群众实际困难，提升群众的满意度？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 4, '是否有利己主义，跟组织讲条件、讨价还价，在名与利、得与失等问题上，能不能够正确对待？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 4, '能不能够做到有问题意识、问题导向，熟悉情况，掌握数据，研究问题，主动解决问题的自觉性和较强的工作能力？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 5, '能不能做到全心全意为人民服务，广泛联系群众，经常与干部职工谈心交流，及时全面直接听取基层群众意见？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 5, '能不能做到遇事接待不讲排场，也不讲个人感情，工作中始终坚持原则？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 5, '能不能做到为政清廉，注意形象，把自己不混同于普通群众，不搞请客送礼、公款吃喝、打牌玩乐、公车私用等？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(1, 5, '能不能做到想群众之所想，急群众之所急，解群众之所困，经常主动问需，特别是在联系服务对象、困难党员、扶贫帮困等方面有突出表现？', 1);
INSERT INTO `PaperQuestion`(`type`, `user_property_id`, `description`, `test_id`) values(2, 1, '你认为你自己活评测对象目前在政治纪律、组织纪律、道德品行、履行义务、模范带头等方面还存在哪些问题？', 1);
INSERT INTO `PaperOption`(`description`,`test_id`, `point`) values('肯定能做到', 1, 5);
INSERT INTO `PaperOption`(`description`,`test_id`, `point`) values('可以做到', 1, 4);
INSERT INTO `PaperOption`(`description`,`test_id`, `point`) values('看情况', 1, 2);
INSERT INTO `PaperOption`(`description`,`test_id`, `point`) values('不能做到', 1, 1);
